kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv
  labels:
    name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: mysql-pv
    fsType: ext4
    readOnly: true

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: mysql-pv

---
# redis
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv
  labels:
    name: redis-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: redis-pv
    fsType: ext4
    readOnly: true

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: redis-pv


---
# file data
kind: PersistentVolume
apiVersion: v1
metadata:
  name: file-data-pv
  labels:
    name: file-data-pv
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: file-data-pv
    fsType: ext4
    readOnly: true

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: file-data-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: file-data-pv